outgoing:
    Global:
        receivers: []
incoming:
    Global:
        sources: []
        target: Global
        format: '[%sender% @ %sourceServer%|%sourceChannel%] %message%'
    SomeRemoteServer.SomeRemoteChannel:
        sources: []
        target: SomeLocalChannel
        format: '[%sender% @ %sourceServer%|%sourceChannel%] %message%'
        