author: DerFlash
database: false
description: CNHeroChatTransporter
main: de.cubenation.plugins.cnherochattransporter.CNHeroChatTransporter
name: CNHeroChatTransporter
startup: postworld
url: http://www.cube-nation.de/
version: '${project.version}'

depend:
  - Transporter
  - Herochat

commands:
  hct:
    description: Manage ...
  
